name = "Synesthesia"
author = "Ashley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1aa6f6becf5d184b0eb1292cf9dbd709e79929429327aefe0ce70bab89e8e30"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
