name = "Synesthesia"
author = "Ashley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d58f92b6ee593205725f2053c2f8853d360df308104c07ca921a33412cfd3ddc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
